repos:
  # 使用 Yelp 的 detect-secrets 工具
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        # args: ['--baseline', '.secrets.baseline']
        # exclude: package-lock.json